//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoNaukaApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int id_applic { get; set; }
        public int id_bank_applic { get; set; }
        public Nullable<int> id_direct { get; set; }
        public string name_customer { get; set; }
        public string address_customer { get; set; }
        public Nullable<int> deadline_days { get; set; }
    
        public virtual DataBank DataBank { get; set; }
        public virtual Classifier Classifier { get; set; }
    }
}
