//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoNaukaApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBankView
    {
        public string Direction { get; set; }
        public string NameOrg { get; set; }
        public string NameBank { get; set; }
        public string Responsibile { get; set; }
    }
}
