//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoNaukaApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsFullInfoView
    {
        public string DataBank { get; set; }
        public string Direction { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public Nullable<int> Deadline { get; set; }
    }
}
